### ISSUE TITLE
Error when trying to compile PlantGL

### ISSUE THREAD

**Issue by chrisdunelm** [fredboudon/plantgl#23]
Hi,

I'm trying to build PlantGL following the instructions in [the "compiling" section of the readme](https://github.com/fredboudon/plantgl#compiling). I'm using Ubuntu Linux 20.04 x64; miniconda 3

I set up the conda environment successfully from the `build-util/plantgl-devel.yaml` file as specified; and `conda activate plantgl-devel`.

However, when I run the first `cmake` invocation I get an error:

```
$ cmake .. -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX}
-- Anaconda environment detected: /home/chris/miniconda3/envs/plantgl-devel
-- Install Prefix: /home/chris/miniconda3/envs/plantgl-devel
-- The CXX compiler identification is GNU 9.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- /home/chris/Projects/ag/plantgl/plantgl/src/cpp/plantgl/version.h
-- PlantGL version : 3.7.0
-- Found Python3: /home/chris/miniconda3/envs/plantgl-devel/bin/python3.9 (found version "3.9.1") found components: Interpreter Development Development.Module Development.Embed 
-- Python version : 3.9.1
-- Python lib : /home/chris/miniconda3/envs/plantgl-devel/lib/libpython3.9.so
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Qt5: Version 5.12.9
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.37") 
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "80") 
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- Found GMP: /home/chris/miniconda3/envs/plantgl-devel/lib/libgmp.so  
-- Found MPFR: /home/chris/miniconda3/envs/plantgl-devel/lib/libmpfr.so  
CMake Error at /home/chris/miniconda3/envs/plantgl-devel/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR) (Required is at least
  version "1.48")
Call Stack (most recent call first):
  /home/chris/miniconda3/envs/plantgl-devel/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  /home/chris/miniconda3/envs/plantgl-devel/share/cmake-3.19/Modules/FindBoost.cmake:2193 (find_package_handle_standard_args)
  /home/chris/miniconda3/envs/plantgl-devel/lib/cmake/CGAL/CGAL_SetupBoost.cmake:20 (find_package)
  /home/chris/miniconda3/envs/plantgl-devel/lib/cmake/CGAL/CGAL_SetupCGALDependencies.cmake:52 (include)
  /home/chris/miniconda3/envs/plantgl-devel/lib/cmake/CGAL/CGALConfig.cmake:128 (include)
  CMakeLists.txt:96 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/chris/Projects/ag/plantgl/plantgl/build/CMakeFiles/CMakeOutput.log".
See also "/home/chris/Projects/ag/plantgl/plantgl/build/CMakeFiles/CMakeError.log".
$
```

The cause appears to be that it cannot find boost, however boost is definitely present in the conda environment - as expected due to the setup from `build-util/plantgl-devel.yaml`

Might you have some idea why this is failing?

Many thanks :)
Chris

**Comment by jvail** [comment]
I used to have a similar problem on debian (but never built inside a conda env) with boost paths. Maybe try setting `Boost_NO_SYSTEM_PATHS` to OFF https://github.com/fredboudon/plantgl/blob/master/CMakeLists.txt#L78

**Comment by chrisdunelm** [comment]
@jvail Thank you for your comment.

As it turned out, I didn't need to alter `Boost_NO_SYSTEM_PATHS`; but have now successfully built the C++ parts of plantgl by using the following conda configuration:
```
channels:
  - conda-forge

dependencies:
  - conda-build=3.18.12
  - cmake=3.16
  - python=3.7
  - ipython=5.8
  - ipykernel=4.10.0
  - configobj=5.0.6
  - nose=1.3.7
  - qt=5.6.2
  - pyqt=5.6.0
  - cgal-cpp=4.14.1
  - ann=1.1.3
  - numpy=1.15.4
  - scipy=1.2.1
  - boost=1.70.0
  - boost-cpp=1.70.0
  - bison=3.4
  - flex=2.6.4
  - matplotlib=3.3.2
  - pandas=1.0.1
```

I'm now able to run the PyTest test-suite, although I'm seeing 26 failures (out of > 500 tests, so fairly successful!)

Do you know if _all_ tests are currently expected to pass? Or should I expect to see some test failures?

I'm currently seeing failures in:
* `test/test_curvemanipulation.py` - CGAL ERROR: assertation violation (note that I'm not using the most recent version of CGAL currently; there are package conflicts if I try to upgrade it, and I haven't yet got to the bottom of what's causing the conflict. Not that upgrading would necessarily fix the problem)
* `test/oatest/test_nodes.py`- Cannot find package : vplants.plantgl.objects (is there some sort of plugin system here that isn't set up correctly?)
* `test/oatest/test_tutorial.py` - TypeError: findCaller() takes 1 positional argument but 2 were given
* `test/ui/test_projpershape.py` - various asserts on numerical values are failing
* `test/ui/test_viewer.py`- AssertionError: Invalid Viewer.selection



Thank you :)

**Comment by jvail** [comment]
Hi @chrisdunelm, I am afraid I am not familiar with the plantgl tests. Guess @fredboudon has an idea. In theory I would expect that all tests that are run in the CI process (linux travis build) are expected to pass. I'd guess this is the relevant part? - not sure though: https://github.com/fredboudon/plantgl/blob/master/conda/meta.yaml#L95

**Comment by chrisdunelm** [comment]
Thanks @jvail 
Perhaps I should explain that my initial goal is to generate (simulated) stands of wheat, so am trying to get the relevant parts of the openalea ecosystem functioning.
It's quite a steep learning curve! And I've been finding it a little difficult to work out where the most up-to-date code and docs are ;)

**Comment by jvail** [comment]
> It's quite a steep learning curve! And I've been finding it a little difficult to work out where the most up-to-date code and docs are ;)

Ok - then it might be easier to just install the relevant parts from conda rather than compiling everything yourself. And maybe https://github.com/jvail/plantgl-jupyter might come in handy for some lpy/plantgl exercises :)

**Comment by chrisdunelm** [comment]
Thank you for your suggestion. I will take a look at the jupyter and conda ways forward. However, I'm keen to understand more deeply how all the parts function and fit together, so will also persevere with a locally built configuration - I'm gradually making progress :)

**Comment by fredboudon** [comment]
Hi Chris,

Compiling plantGL is not trivial indeed. Using directly the package from anaconda should be the simplest way to use plantGL.
For the tests, test in subdirs ui and oatest are non optional and are not guarantee to work (as they may require additional dep).

**Comment by chrisdunelm** [comment]
Thanks @fredboudon 
Is there a list of all the required dependencies (+versions) somewhere?

**Comment by fredboudon** [comment]
The most up to date version of dependencies description is in conda/meta.yml.
But you find build environment yaml files in build-util (https://github.com/fredboudon/plantgl/blob/master/build-util/plantgl-devel.yaml). No specific version is usually used for packages (last one is used). Except for boost where v 1.74 seems to not compile on windows. so we avoid it.

**Comment by chrisdunelm** [comment]
Thanks :)
