### ISSUE TITLE
bgeom serialization seem to ignore groups

### ISSUE THREAD

**Issue by jvail** [fredboudon/plantgl#24]
After encoding and decoding the scene to/from bgeom it seems to be empty:

```python
import openalea.plantgl.all as pgl
group = pgl.Group([pgl.Sphere(), pgl.Sphere()])
assert len(pgl.Scene([group])) == 1
assert len(pgl.frombinarystring(pgl.tobinarystring(pgl.Scene([group])))) == 1
```

Reported here https://github.com/jvail/plantgl-jupyter/issues/52

**Comment by fredboudon** [comment]
resolved in commit 06112ae730d14e3f4d3a33b897efb9f836e23fde
